### ISSUE TITLE
Release workflow is not working

### ISSUE THREAD

**Issue by zhfeng** [quarkiverse/quarkus-dapr#151]
see https://github.com/quarkiverse/quarkus-dapr/actions/runs/7758163252/job/21159279801

**Comment by zhfeng** [comment]
And it could impact other repos as well.

**Comment by gastaldi** [comment]
@zhfeng your `docs` module is missing the pom.xml. Copy from what's generated with `quarkus create extension dapr`

**Comment by zhfeng** [comment]
Hmm, it looks like we don't have it for a long time!

**Comment by mcruzdev** [comment]
Hi @zhfeng, how are you? I added the pom.xml to the extension, can you review it? #162
