### ISSUE TITLE
Remove examples projects from Maven publish step

### ISSUE THREAD

**Issue by mcruzdev** [quarkiverse/quarkus-dapr#165]
Actaullty, the example projects are being published alongside the extension.

**Comment by zhfeng** [comment]
@mcruzdev you mean the `demo` project? I think we had excluded it.

**Comment by mcruzdev** [comment]
Hi @zhfeng, yeah, does it make sense?

**Comment by zhfeng** [comment]
Sure, it has been excluded. see https://github.com/quarkiverse/quarkus-dapr/blob/507de9bc9206b6bc55b001be7764d10589aa531c/pom.xml#L81-L93

**Comment by mcruzdev** [comment]
I saw the possibility of installing the `demo`, but it can be a mistake, sorry @zhfeng

I think that we can close it.
