### ISSUE TITLE
Make sure github CI is working

### ISSUE THREAD

**Issue by zhfeng** [quarkiverse/quarkus-dapr#3]
@gastaldi can you help cheking the CI setting? It seems that it can not trigger the PR building automatically now.

**Comment by gastaldi** [comment]
That's because it's configured to build the `main` branch. Please rename the master branch to main too

**Comment by zhfeng** [comment]
Thanks @gastaldi!

@naah69 can you take care of rename the master branch to main? Refer to https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch

**Comment by gastaldi** [comment]
@zhfeng I just did it :) Hope it works now

**Comment by naah69** [comment]
yes ,i will change it

**Comment by naah69** [comment]
> @zhfeng I just did it :) Hope it works now

thanks for your help 😁

**Comment by gastaldi** [comment]
The workflow file was misaligned (YAML is so nice, isn't it? :)

I'm checking if our tooling is generating it correctly. Thanks.for reporting this

**Comment by zhfeng** [comment]
Thanks @gastaldi! CI is working now.
