### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by zhfeng** [quarkiverse/quarkus-dapr#4]
We need to update it with the details about this extesion.

- brief of the dapr
- some examples about how to use the ```dapr-client``` in this extension

**Comment by zhfeng** [comment]
@skyao can you check it ?

**Comment by gastaldi** [comment]
Also have docs under a `docs/` directory using the Antora format (a sample should be aleeady generated if you created the extension skeleton using the `quarkus create extension` CLI). See https://github.com/quarkiverse/quarkus-amazon-services/tree/main/docs for an example and https://github.com/quarkiverse/quarkiverse-docs/pull/32/files for an example on how to get it included in the [Quarkiverse Docs website](https://quarkiverse.github.io/quarkiverse-docs/index/index/index.html)

**Comment by zhfeng** [comment]
@gastaldi please can you invite @skyao to join the qurkiverse org? And I think he is intersting with the ```quarkus-dapr``` extension. Thanks!

**Comment by gastaldi** [comment]
@zhfeng of course, I created a PR in https://github.com/quarkiverse/quarkiverse-devops/pull/46. 

Can someone in the @quarkiverse/quarkiverse-dapr team approve it? 

BTW I forgot to mention that changes to the repository (new team members, description, homepage URL, etc) should be performed in the Terraform scripts in https://github.com/quarkiverse/quarkiverse-devops/ as PRs (from branches in the same repository, not forks). If there are external changes not reflected there, it could be undone at any time 😉

**Comment by zhfeng** [comment]
yeah, I approve it. Hmm, another tool I need to learn :)

**Comment by zhfeng** [comment]
It looks awesome!

**Comment by gastaldi** [comment]
@all-contributors add @zhfeng for code and maintenance

**Comment by zhfeng** [comment]
@all-contributors add @skyao for code and maintenance

**Comment by zhfeng** [comment]
@all-contributors add @skyao for code and maintenance

**Comment by skyao** [comment]
I have udpated the read file to add introduction of quarkus dapr extension and add examples.

**Comment by zhfeng** [comment]
Thanks @skyao and it looks awesome!
