### ISSUE TITLE
Prepare for Quarkus 3.x

### ISSUE THREAD

**Issue by zhfeng** [quarkiverse/quarkus-dapr#68]
Refer to https://github.com/quarkiverse/quarkiverse/wiki/Migrating-to-Quarkus-3.x#upgrade

**Comment by zhfeng** [comment]
@naah69 Would you like to take care of migrating to Quarksu 3?

**Comment by naah69** [comment]
pr in https://github.com/quarkiverse/quarkus-dapr/pull/89
we should release it for 3.x

**Comment by mcruzdev** [comment]
Hi @naah69, how are you?

This issue was solved?

**Comment by zhfeng** [comment]
We release `2.0.0` for Quarkus 3.x
