### ISSUE TITLE
Add a native build step in CI

### ISSUE THREAD

**Issue by zhfeng** [quarkiverse/quarkus-dapr#7]
It needs to verify the native build is working.

**Comment by naah69** [comment]
add it in [commit](https://github.com/quarkiverse/quarkus-dapr/commit/735754d70e0c1cb57c47e26b9e2b9e178108b8f1)

**Comment by naah69** [comment]
it works now.

**Comment by zhfeng** [comment]
Thanks @naah69 and please don't push a commit directly into the ```main``` branch but raise a PR.
