### ISSUE TITLE
Make Topic configurable 

### ISSUE THREAD

**Issue by tillganster** [quarkiverse/quarkus-dapr#85]
Hello,

Is it possible to use a topic name which can be configured by an environment variable? If use simply use the `@Topic` Annotation there is a compile time constant needed. 

I also tried to use the following syntax but then the topic `topicName` is used instead of the Topic which is vonfigured in `topic.name`
```Java
    @Inject
    @ConfigProperty(name = "topic.name")
    lateinit var topicName: String

    @POST
    @Path("/handle")
    @Topic(name = "\${topicName}",  pubsubName = "redis-pubsub")
    override fun handleMailEvent(event: CloudEvent<Mail>): String { ... }
```

Is there any other option to subscribe to a topic ?

**Comment by naah69** [comment]
it can be implemented by developing ${topic.name},but it will not change when application is running,just onstart.
welcome to pr it.

**Comment by mcruzdev** [comment]
Hi @naah69
I think that I can to contribute with it.

**Comment by naah69** [comment]
ok,welcome to contribute it.

**Comment by mcruzdev** [comment]
I think that we can close it @naah69
